### ISSUE TITLE
i created a video wallpaper ,but it doesn't appear 

### ISSUE THREAD

**Issue by chemel9** [iabem97/komorebi#101]
Hi, i created a video wallpaper , using wallpaper creator , and i follow the instructions, to copy the wallpaper folder to komerebi folder
but when i want to choose the wallpaper, it doesn't appear.
could you help me?

![deepinscreenshot_dde-file-manager_20180216140926](https://user-images.githubusercontent.com/26883220/36327099-2454605c-1323-11e8-8024-45e10d43fda4.png)
![deepinscreenshot_dde-file-manager_20180216140947](https://user-images.githubusercontent.com/26883220/36327100-247235f0-1323-11e8-9b9e-b8a0eeb3ccb5.png)
![deepinscreenshot_komorebi_20180216140907](https://user-images.githubusercontent.com/26883220/36327101-248bb7a0-1323-11e8-9c2a-58a0d60cdae6.png)

**Comment by tehpenguin** [comment]
You have to change the name of thumbnail.jpg to wallpaper.jpg in the file.

**Comment by thedonquixotic** [comment]
@chemel9 If your issue is fixed please close this thread.

**Comment by iabem97** [comment]
Thank you for reporting the issue. Next push will resolve this.
