### ISSUE TITLE
Wallpaper list is not updating

### ISSUE THREAD

**Issue by colin-haeberle** [iabem97/komorebi#103]
Hi every one,
I tried to create a video wallpaper on a Debian Stretch. So i download your paquet and install it. All seems function, i create the wallpaper with no issues during the creation, after what i move the folder created in the /System/Ressources/Komorebi folder. But when i try to change the wallpaper by the new one that i created, this one does not appear in the list. What i have to do to fix it?
Thanks in advance!

**Comment by pedraero** [comment]
Same issue.

**Comment by lectrode** [comment]
In the generated folder, I had to manually rename "thumb.jpg" to "wallpaper.jpg" for the new ones to appear. After that, it seems to work like it should. Using AUR package on Manjaro Linux.

**Comment by schippie** [comment]
@lectrode that fixed it for me, thank you!

**Comment by Yakumo-Yukari** [comment]
I'm the same problem.

**Comment by Yakumo-Yukari** [comment]
@lectrode  thx

**Comment by thedonquixotic** [comment]
This fixed it for me too. I see a bunch of duplicate threads with this problem. I also I had this problem. @colin-haeberle could you please close this thread so we can tidy up this repo some? Reduce the noise to signal ratio. I'm going to do a pull request to add this information to the documentation. 

Doesn't seem like this would be a difficult thing to fix. I'm a coder learning to program and I'm a pretty bad programmer, but I think I might be able to figure out how to make this fix official. It seems like it's a pretty simple issue.

**Comment by iabem97** [comment]
Thank you for reporting the issue. Next push will resolve this.
