### ISSUE TITLE
Wallpaper Creator not showing wallpaper options. 

### ISSUE THREAD

**Issue by JettScythe** [iabem97/komorebi#105]
Well, I tried to add a custom gif as a wallpaper. It's the only reason I want this program. Unfortunately I am met with this, and even if I continue and copy the folder to the proper location, the wallpaper creator does not update. 

![deepinscreenshot_komorebi-wallpaper-creator_20180318231732](https://user-images.githubusercontent.com/37233887/37574895-ea764a7e-2b1b-11e8-8b60-8b6e99014f7b.png)

**Comment by JettScythe** [comment]
If it makes any difference to you: 
OS: Manjaro Linux x86_64
Host: K55VD 1.0
Kernel: 4.15.8-1-MANJARO
Uptime: 11 hours, 8 mins
Packages: 1189
Shell: bash 4.4.19
Resolution: 1366x768
DE: Cinnamon 3.6.6
WM: Mutter (Muffin)
WM Theme: Utnapishtim Zorin (Adwaita-dark)
Theme: Utnapishtim Zorin [GTK2/3]
Icons: Vibrancy-Dark-Teal [GTK2/3]
                               Terminal: gnome-terminal
                               CPU: Intel i7-3630QM (8) @ 3.400GHz
                               GPU: Intel Ivybridge Mobile
                               GPU: NVIDIA GeForce 610M
                               Memory: 3781MiB / 7865MiB

Also running Conky, Firefox Developers Edition, and discord as this happens.

**Comment by thedonquixotic** [comment]
I'm having similar issues :(

Ubuntu 18.04

**Comment by thedonquixotic** [comment]
I have found a solution to this issue in this thread: https://github.com/iabem97/komorebi/issues/103

@JettScythe please close this thread so that we can reduce the noise to signal ratio of the repo.
