### ISSUE TITLE
How to use on multiple screens at the same time?

### ISSUE THREAD

**Issue by RikiFly** [iabem97/komorebi#107]
My work computer has two screens, but it will only work on one of the screens.

**Comment by liqifei007** [comment]
Im sorry. Just video can not be displayed on two screens
Maybe you guys can help me.
thanks.

**Comment by Hammer2900** [comment]
Yes, why you use only main screen ? Any comments )

**Comment by shrgabor** [comment]
I'm using on Ubuntu 16.04 two monitors with gnome desktop environment.
Clock only displayed on the main monitor, also the desktop icons and the right click menu is only working on the main monitor.

**Comment by thedonquixotic** [comment]
@juceliohv please close this issue. There is a fix for this already in the pull requests, but the project maintainer has seemingly abandoned the project. If you are interested I have created a fork which I intend to help maintain. If you'd be interested in contributing check out: https://github.com/thedonquixotic/komorebi

**Comment by thedonquixotic** [comment]
@RikiFly  please close this issue. There is a fix for this already in the pull requests, but the project maintainer has seemingly abandoned the project. If you are interested I have created a fork which I intend to help maintain. If you'd be interested in contributing check out: https://github.com/thedonquixotic/komorebi

**Comment by iabem97** [comment]
Thank you for reporting the issue. Next push will resolve this.
