### ISSUE TITLE
Dual monitors - komorebi hides when clicking on other monitor

### ISSUE THREAD

**Issue by npanagop** [iabem97/komorebi#11]
On a dual monitor setup, komorebi launches on the default primary(left most screen) display. I can tell it does not run on the second display cause there are no animations.

If I click on the second display nautilus comes to the foreground on both displays and komorebi is left running on the background with no way to bring it back.

If you need any info about my hardware let me know.
Love the app, too bad I can't use it on my desktop.

**Comment by npanagop** [comment]
Seeing the previous closed issue on dual monitors(my bad I didn't check before posting) I understand why it runs on one monitor only. I guess nautilus overtaking komorebi when clicking on another monitor is inevitable?

**Comment by iabem97** [comment]
So I tried this on a computer with dual monitors and it did disappear for me as well.
What's happening is that when you click somewhere else, nautilus grabs focus and puts Komorebi behind it.

Suggestion: Disable nautilus from drawing icons and background using GNOME Tweak Tool for now.

Does the suggestion work for you? I understand you won't have desktop icons anymore but it won't cause Komorebi to hide again. I am working on adding icons to Komorebi in the future by default.

**Comment by npanagop** [comment]
I had some issues with GNOME tweak tool, so I simply launched nautilus with --no-desktop option. This fixes the issue mentioned above :+1: 

Maybe in the future you could add the ability to choose a monitor to display the text and animations in multi-monitor setups.

**Comment by iabem97** [comment]
Thank you for your suggestion! I will add that to the list of things that will come with newer versions of Komorebi.
