### ISSUE TITLE
Won't run in Ubuntu 18.04

### ISSUE THREAD

**Issue by galderson** [iabem97/komorebi#120]
Ubuntu 18.04 64-bit
Doesn't open.

**Comment by rauldipeas** [comment]
This fix to me:
`cd /usr/lib/x86_64-linux-gnu`
`sudo ln -s libgtop-2.0.so.11 libgtop-2.0.so.10`

**Comment by Trilokia** [comment]
Thanks a lot :)

**Comment by vdlald** [comment]
> This fix to me:
> `cd /usr/lib/x86_64-linux-gnu`
> `sudo ln -s libgtop-2.0.so.11 libgtop-2.0.so.10`

doesn't work for me

**Comment by HakanIlbas** [comment]
I posted a fix in #213
