### ISSUE TITLE
Can't right click after installing/removing komorebi

### ISSUE THREAD

**Issue by gideonidoru** [iabem97/komorebi#13]
Hi, I cant right click on my desktop or drag to select. I installed, then removed komorebi and my desktop is essentially dead. I can change wallpapers but that's it.

Linux Mint Serena with Cinnamon

**Comment by iabem97** [comment]
Icons support is coming soon to Komorebi. Right now, Komorebi disables nautilus/other software from handling icons.
You can re-enable icons by running the following in terminal:
gsettings set org.gnome.desktop.background show-desktop-icons true

Please let me know if that fixes your issue.

**Comment by gideonidoru** [comment]
It did not fix my issue. Additionally turning icons on and off through the settings interface for cinnamon does nothing. I cant click+drag to create a selection area or right click either. Its as iff my background is dead for interaction.

It's important to note I removed the app and this is still occuring.

**Comment by gideonidoru** [comment]
Any updates?

**Comment by iabem97** [comment]
@gideonidoru that is actually very strange. The only thing **Komorebi** is disabling is 'show-desktop-icons'.
Are you using **nemo** or **nautilus**?
If nemo, can you try: `gsettings set org.nemo.desktop show-desktop-icons false`
If that doesn't work, can you try changing your background?

Please let me know if that fixes your issue.

**Comment by gideonidoru** [comment]
Setting that to "true" fixed it! And brought back my ability to right click! Is this something you can fix through your apt remove script?

**Comment by iabem97** [comment]
Oh I meant true instead of false.
Either Way, the cause of the issue is weird since the code never sets org.nemo.desktop to anything, but I'll make it add the functionality to the code.

Thanks for sharing that out!

**Comment by MoriGM** [comment]
Write gsettings set org.gnome.desktop.background picture-uri /path/to/wallpaper
To get the Desktop icons back.

**Comment by jdspaeth** [comment]
had to use **gsettings set org.nemo.desktop show-desktop-icons true** after uninstalling as well - on Linux Mint 19.1 Cinnamon

**Comment by AdrienHorgnies** [comment]
@cheesecakeufo That would be nice if Komorebi could save all the system settings it modified and put them back when it is uninstalled. Or at least list them when you installed komorebi or launch it for the first time.
