### ISSUE TITLE
Unistall

### ISSUE THREAD

**Issue by shaileshgoogler** [iabem97/komorebi#14]
How do I uninstall this package? Installed using installation package manager.

**Comment by iabem97** [comment]
Sorry for the delayed response!
Komorebi doesn't have an uninstall script yet, but you can simply remove it by deleting its directory:
`sudo rm -rf /System/Resources/Komorebi`
and
`sudo rm -rf /System/Applications/komorebi`

The commands above should remove Komorebi from your system
