### ISSUE TITLE
Not fitting to screen

### ISSUE THREAD

**Issue by derpyderpaderp** [iabem97/komorebi#19]
I am having an issue with it simply not going fully a cross the screen Unsure why it is doing this. This is on Manjaro XFCE Edition (17.0.1) and are fairly new to arch so not sure what to do. Any help would be greatly appreciated. 
I will post a link to a video of the problem I'm having I hope it helps. 
https://www.youtube.com/watch?v=0QZwHlGaVgc&feature=youtu.be

**Comment by iabem97** [comment]
@derpyderpaderp What is your monitor setup like? Also, what does Komorebi output in the terminal show?

I haven't tested Komorebi in Arch myself but I do believe there are Arch users who've tried it out with no issues.

**Comment by derpyderpaderp** [comment]
I have found out where the issue is coming from. It is a bug that has been with Lightdm for a long time. I just switched over to sddm for now until the bug is fixed. Marking as closed.
