### ISSUE TITLE
Dependency not included in .deb package

### ISSUE THREAD

**Issue by Rafael8661** [iabem97/komorebi#22]
I just installed komorebi with the .deb package on KDE Neon LTS 6.8 (Linux distro based on Ubuntu 16.04) and cannot run it. When ran in the terminal I got an error about ibgtop-2.0-10.so lib not found. So I just installed it like this: 
`sudo apt-get install ibgtop-2.0-10`
and now is working fine. Of course, it's not a big problem, but you might want to add this as a dependency in the .deb package on the next release. I only made this post as an advice for other people in the same problem and for you (developer) be aware of this.
Besides that, excellent app, good job. ;-)

**Comment by iabem97** [comment]
Thank you for noticing that! It looks like I missed a comma in the CMake file that caused cmake to miss the dependency when packaging Komorebi into a debian package.
Issue has been fixed and will be updated in the next release. Thank you!! :)
