### ISSUE TITLE
stop tracking mouse

### ISSUE THREAD

**Issue by Rimesh** [iabem97/komorebi#23]
This is very cool wallpaper.
however is it possible to stop tracking mouse movements?
Static date and time display would be better.

**Comment by amasriSF** [comment]
@Rimesh I'm currently working on a major overhaul of Komorebi. The current mechanics behind mouse tracking will eventually be replaced.
I will update this once the code is pushed.
______
Thank you.

**Comment by Rimesh** [comment]
Thank you! :)
