### ISSUE TITLE
Komorebi won't launch in Xubuntu 17.04

### ISSUE THREAD

**Issue by guptaanmol184** [iabem97/komorebi#26]
I used the [Komorebi.for.64-bit.deb](https://github.com/iabem97/komorebi/releases/download/0.9.2/Komorebi.for.64-bit.deb) installer from the [releases page](https://github.com/iabem97/komorebi/releases).

It installs just fine.
But on launching it doesn't launch at all.

**Comment by amasriSF** [comment]
Can you please run it manually through the terminal and paste the output here?
You can run it by opening **Terminal**, copy and paste the following:
`/System/Applications/komorebi`
Then hit **Return/Enter**
What is the output you're getting?
Thank you!

**Comment by iabem97** [comment]
Can you please run it manually through the terminal and paste the output here?
You can run it by opening **Terminal**, copy and paste the following:
`/System/Applications/komorebi`
Then hit **Return/Enter**
What is the output you're getting?
-------------
Thank you!

**Comment by guptaanmol184** [comment]
I made it manually from source.
Needed to reboot my system to make it work.
Now it works. 
Great work! :+1:

**Comment by Hermlon** [comment]
Same with me. Error is: `/System/Applications/komorebi: error while loading shared libraries: libgtop-2.0.so.10: cannot open shared object file: No such file or directory`
