### ISSUE TITLE
Unable to install it on Fedora + KDE Plasma

### ISSUE THREAD

**Issue by Warmuser** [iabem97/komorebi#28]
I tried to download and install the package manually but the dpkg is not present in the system. Otherwise I tried with the Discover app, but the installation doesn't start. Any suggestion? Thanks

PS: I'm on Fedora 26 + KDE Plasma 5.10

**Comment by Warmuser** [comment]
@iabem97 wow, perfect. Thank you!! :)

**Comment by iabem97** [comment]
The new Komorebi has been released! If you have dpkg installed, try using the packaged version. If not, you can build it manually. Checkout the tutorial on the home page!

**Comment by ways** [comment]
Worked for me by installing dependencies:

> sudo dnf install clutter-gtk-devel clutter-gst-devel libgtop2-devel gtk3-devel gtk+-devel clutter-gst3-devel libgee-devel libgee gstreamer1-libav

Converting the package to rpm:
> sudo alien --to-rpm --scripts komorebi-2-64-bit.deb

And running it from the weird place it ended up:
> $ /System/Applications/komorebi

System: fedora 26 with kde.

**Comment by amasriSF** [comment]
Perfect! Thanks for sharing the steps!

**Comment by iabem97** [comment]
Perfect! Thanks for sharing the steps!

**Comment by Warmuser** [comment]
I finally installed Komorebi on Arch Linux and It works perfectly, thanks! ;) I just want to leave my feedback.
