### ISSUE TITLE
Need to improve the gstreamer1.0-libav check

### ISSUE THREAD

**Issue by wangxa** [iabem97/komorebi#29]
Hi,

I read your Utilities.vala's canPlayVideos () function. It seems the absolute paths used to detect the existence of gstreamer1.0-libav don't work for Fedora. In Fedora, the path is 
```bash
/usr/lib64/gstreamer-1.0/libgstlibav.so
```

**Comment by iabem97** [comment]
Awesome. Just added a check for `/usr/lib64/gstreamer-1.0/libgstlibav.so`
Thank you for reporting the bug!
