### ISSUE TITLE
Can't access custom made wallpaper

### ISSUE THREAD

**Issue by Dugy** [iabem97/komorebi#36]
I created a wallpaper based on my old background and its folder was created in my home directory with the config file and background picture (not in any `/System/Resources/Komorebi/`, there is no such folder in Ubuntu anyway), but when I opened the select background window, it wasn't there. I edited its configuration file to use my background, but I got black screen instead.

I believe that this problem is caused by the absence of the `/System/Resources/Komorebi/` folder where it should be located on Ubuntu.

I am using Ubuntu 16.04.

**Comment by PizzicatoWolf** [comment]
also affects me too

**Comment by PizzicatoWolf** [comment]
I just checked and it seems to have placed it in the root directory.

**Comment by amasriSF** [comment]
Komorebi is installed in `/System/` and all wallpapers can be located in `/System/Resources/Komorebi/xx_your_wallpaper_name_xx`
Simply, move the folder created by Wallpaper Creator to `/System/Resources/Komorebi/` then your wallpaper will be visible in the list of wallpapers!

Let me know if that works!

**Comment by iabem97** [comment]
Komorebi is installed in /System/ and all wallpapers can be located in /System/Resources/Komorebi/xx_your_wallpaper_name_xx
Simply, move the folder created by Wallpaper Creator to /System/Resources/Komorebi/ then your wallpaper will be visible in the list of wallpapers!

Let me know if that works!

**Comment by Dugy** [comment]
I thought it said that `the/System/Resources/Komorebi/`  folder would be in my home folder.

The wallpaper editor did not have the rights to create and edit files in that folder, owner was root and anyone else could only access the files. As a result, it created the settings in the home folder instead for whatever reasons.

**Comment by ErikWallstrom** [comment]
A fix I found was renaming the video file to `video.mp4` and the wallpaper to `wallpaper.jpg` and also editing the config

**Comment by thedonquixotic** [comment]
This issue has a fix in a pull request waiting to be accepted by the owner of this repo. In the meantime can you please close this ticket @Dugy

**Comment by Dugy** [comment]
Okay.
