### ISSUE TITLE
Debian packages issue

### ISSUE THREAD

**Issue by mhalano** [iabem97/komorebi#38]
The Komorebi 2.0 Debian package is populating files on /System/{Applications,Resources} which is clearly macOS directories, not Linux directories.

**Comment by iabem97** [comment]
The directories aren't referring to macOS. Komorebi follows the structure of Kedos OS (Unreleased operating system).
Having the files in /System shouldn't really cause any issues. If so, please let me know.

I'll close this since it's not really an issue. Thank you :)

**Comment by mhalano** [comment]
The issue is: there's no command on terminal do call the application because 'komorebi' command is in /System/Applications and not on /usr/bin.
