### ISSUE TITLE
Komorebi 2 Breaks Dash to Panel on Ubuntu Gnome 17.04

### ISSUE THREAD

**Issue by TylerCode** [iabem97/komorebi#46]
When using Komorebi, I get an issue where I cannot see my bottom bar anymore. More specifically, I see the bar, but my open programs no longer show on it as seen in the attached screenshot. 

This seems to happen if I lock the screen and come back or sometimes when just using the computer (I noticed it happened when I changed my wallpaper and once randomly when I looked away for a minute)

For me it's not the end of the world as a restart will fix it but it is slightly annoying to have to press the super key to switch programs. 

![selection_006](https://user-images.githubusercontent.com/18288340/30224773-48be2442-948d-11e7-8254-befca765ca56.png)

To correct this, I have tried re-installing Komorebi.

Software versions are as follows.

Ubuntu Gnome 17.04
Dash to Panel 9
Dynamic Panel Transparency v20

Possibly Unrelated but other extensions are:
Removable Drive Menu
MConnect

Let me know how I can help.

**Comment by TylerCode** [comment]
Wanted to post how it normally looks. 

Thanks again.

![selection_007](https://user-images.githubusercontent.com/18288340/30242411-341c2784-9553-11e7-9382-37c06cdc9967.png)

**Comment by iabem97** [comment]
Thanks for the bug report.
I've tried to replicate the issue by installing Dash to Panel and running Komorebi but I couldn't replicate the issue.
Also tried changing wallpapers, locking my computer with no luck of being able to reproduce it.

See the following screenshot:
![screenshot from 2017-09-09 22-01-37](https://user-images.githubusercontent.com/2975241/30245804-fbe4614e-95aa-11e7-818e-7eb8ed5f2170.png)

Have you tried re-installing Dash to Panel?

**Comment by TylerCode** [comment]
I'll give that a shot. After chasing it down a bit this weekend, it might actually be an issue with dynamic transparency. This is a fresh install and my first time back to gnome in a while. I'll report back and if I don't find a reliable way to replicate it or if it's something else I'll let you know so you can at least close the issue.

Thanks for the fast response.

**Comment by TylerCode** [comment]
I haven't been able to make it happen again. I'm not entirely sure what changed but its all fine now. I think it may have been an issue with Dash to Panel but oh well. I'm going to close this one.
