### ISSUE TITLE
Desktop Icons gone - Can't use Desktop anymore

### ISSUE THREAD

**Issue by ghost** [iabem97/komorebi#61]
Hey, 

just tried out Komerobi and after uninstalling, i can't use my desktop anymore. I use Mint Cinnamon. 

I can't see any icons or use right-click menus on it. Rebooting didn't help and neither did changing desktop settings.

Any ideas? Thanks

**Comment by davidfur** [comment]
I have the same problem with ubuntu

**Comment by anthonymasset** [comment]
Same problem for me on Ubuntu 17.04

**Comment by anthonymasset** [comment]
Solved for me using this command :
`gsettings set org.gnome.desktop.background show-desktop-icons true`

**Comment by jmarcorb** [comment]
Same for my Ubuntu 16.04 64bit. The solution provided by @anthonymasset worked. Thanks!

**Comment by linusg** [comment]
For me, this did it on LM Cinnamon 18:

    gsettings set org.nemo.desktop show-desktop-icons true

because of this line: https://github.com/iabem97/komorebi/blob/master/src/Utilities.vala#L223

**Comment by iabem97** [comment]
I apologize for the missing removal script. I've pushed a fix to the latest version of Komorebi already.
You can simply run the removal script manually with:
`curl -s https://raw.githubusercontent.com/iabem97/komorebi/master/data/Other/postrm | bash -s`

**Comment by rustombhesania** [comment]
@anthonymasset 
myself using ubuntu 18.04 after uninstalling komorebi ( some live wallpaper application ) 
all the icons were removed also right is not working 
after running this :
gsettings set org.gnome.desktop.background show-desktop-icons true

#coment it shows this:

GLib-GIO-Message: 01:56:50.667: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(process:2894): GLib-GIO-WARNING **: 01:56:50.667: unknown schema extension 'd'

(process:2894): GLib-GIO-WARNING **: 01:56:50.667: unknown schema extension 'd'
 

#comment nothing happens

**Comment by rustombhesania** [comment]
@cheesecakeufo 
myself using ubuntu 18.04 after uninstalling komorebi ( some live wallpaper application )
all the icons were removed also right is not working
after running this :
gsettings set org.gnome.desktop.background show-desktop-icons true

#coment it shows this:

GLib-GIO-Message: 01:56:50.667: Using the 'memory' GSettings backend. Your settings will not be saved or shared with other applications.

(process:2894): GLib-GIO-WARNING **: 01:56:50.667: unknown schema extension 'd'

(process:2894): GLib-GIO-WARNING **: 01:56:50.667: unknown schema extension 'd'

#comment nothing happens

**Comment by LannesL** [comment]
Same issue on LM 20 with cinn.
How do I repair this?

**Comment by kingaspx** [comment]
same issue on Ubuntu 20.10
