### ISSUE TITLE
Cannot change unity wallpaper after komorebi2 uninstall 

### ISSUE THREAD

**Issue by anterak13** [iabem97/komorebi#62]
hi, under 16.04 with unity7, after uninstalling komorebi-2-64-bit.deb, I cannot change the wallpaper anymore (I'm stuck with the default ubuntu wallpaper).
It seems the desktop stays hijacked even after uninstall, can't right click and get a contextual menu anymore on the desktop background.
Does komorebi modify any global gconf settings ?

**Comment by anthonymasset** [comment]
Same problem for me on Ubuntu 17.04.

**Comment by AlaaMHossam** [comment]
same here ubuntu 17.04

**Comment by AlaaMHossam** [comment]
same here ubuntu 17.04

**Comment by anthonymasset** [comment]
Solved for me using this command :
`gsettings set org.gnome.desktop.background show-desktop-icons true`

**Comment by mrccnt** [comment]
This fix also works on Ubuntu 16.04 LTS

**Comment by anterak13** [comment]
I checked the vala source code and found some code that might alter global settings, here:

       /* Fixes conflicts with other environmnets */
	void fixConflicts() {

		// Disable/Enabled nautilus to fix bug when clicking on another monitor
		new GLib.Settings("org.gnome.desktop.background").set_boolean("show-desktop-icons", false);

		// Check if we have nemo installed
		SettingsSchemaSource settingsSchemaSource = new SettingsSchemaSource.from_directory ("/usr/share/glib-2.0/schemas", null, false);
		SettingsSchema settingsSchema = settingsSchemaSource.lookup ("org.nemo.desktop", false);

		if (settingsSchema != null)
			// Disable/Enable Nemo's desktop icons
			new GLib.Settings("org.nemo.desktop").set_boolean("show-desktop-icons", false);


	}

And here:

        var mainSettings = Gtk.Settings.get_default ();
        mainSettings.set("gtk-xft-dpi", (int) (1042 * 100), null);
        mainSettings.set("gtk-xft-antialias", 1, null);
        mainSettings.set("gtk-xft-rgba" , "none", null);
        mainSettings.set("gtk-xft-hintstyle" , "slight", null);

**Comment by iabem97** [comment]
Related to #61 :
I apologize for the missing removal script. I've pushed a fix to the latest version of Komorebi already.
You can simply run the removal script manually with:
`curl -s https://raw.githubusercontent.com/iabem97/komorebi/master/data/Other/postrm | bash -s`

**Comment by MoriGM** [comment]
gsettings set org.gnome.desktop.background picture-uri /path/to/wallpaper
That fixed the error
