### ISSUE TITLE
Wallpaper is shown for milliseconds when changing workspaces in elementary OS

### ISSUE THREAD

**Issue by capstan1** [iabem97/komorebi#63]
See screencast here:
https://drive.google.com/open?id=0B2lRaFHoTHleMndnLWVXZXlFT2M

**Comment by iabem97** [comment]
This seems to be an issue related to how elementary os handles workspace switching for apps like Komorebi.
Since this issue doesn't happen on GNOME or Unity, I can't do anything about it :/
