### ISSUE TITLE
Update interval for CPU consumption

### ISSUE THREAD

**Issue by Shivang44** [iabem97/komorebi#7]
Komorebi uses ~3% CPU constantly while its running. Personally, I don't care for the animation part of this wallpaper, but I *really* like the wallpapers and how the text is partially hidden.

I would love to see an option to disable animations and also set the update interval for the time to every 60 seconds to reduce CPU usage. 

Thoughts?

**Comment by iabem97** [comment]
You can disable animation for a specific wallpaper by going to the wallpaper folder itself in **/System/Resources/Komorebi/your_wallpaper_name** then open **config**
Set AnimationMode value to noanimation
`AnimationMode=noanimation`

Another reason of high CPU consumption is the large wallpapers size, I am going to compress all wallpapers so their size will be less and CPU usage will also go down.
