### ISSUE TITLE
Not able to roll back to old desktop changes

### ISSUE THREAD

**Issue by poddardelhi** [iabem97/komorebi#72]
I'm facing same challenge after uninstallation. My destop is showing black wallpaper with no icons.

**Comment by karanrajpal14** [comment]
If you're on Ubuntu, have a look at the solution I posted in #68, it should help. If not, look for something similar for your distro.

**Comment by poddardelhi** [comment]
I fixed it through graphical.

**do this with graphical program, dconf editor.
You would simply follow the same path as laid out above.
org > gnome > desktop > background > check/uncheck show-desktop-icons**

Source [https://ubuntuforums.org/showthread.php?t=2246432](url)
