### ISSUE TITLE
[Wonderful idea] Support for vghd and istripper animated shows? 

### ISSUE THREAD

**Issue by Warmuser** [iabem97/komorebi#77]
Please, @iabem97 can you implement Komorebi with the possibility to run these kind of animated shows?

**Comment by iabem97** [comment]
This will turn the application into an R-rated one. I don't think I'd like that.
You have the option to create your own custom video wallpapers for personal use, but I would not like to see nudity in Komorebi by default.

Thank you for your idea. Closing.
