### ISSUE TITLE
glib.h not found

### ISSUE THREAD

**Issue by bksubhuti** [iabem97/komorebi#8]
I tried to install, and added the dependencies.  
but glib.h was not found
canning dependencies of target komorebi
[ 28%] Building C object CMakeFiles/komorebi.dir/src/Main.c.o
/home/bksubhuti/komorebi/build/src/Main.c:21:18: fatal error: glib.h: No such file or directory
compilation terminated.
CMakeFiles/komorebi.dir/build.make:82: recipe for target 'CMakeFiles/komorebi.dir/src/Main.c.o' failed
make[2]: *** [CMakeFiles/komorebi.dir/src/Main.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/komorebi.dir/all' failed
make[1]: *** [CMakeFiles/komorebi.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by iabem97** [comment]
There's something really weird about CMake and glib. You can actually fix it by running 'cmake ..' twice, then build.

**Comment by bksubhuti** [comment]
Thanks.. I actually ran cmake another time before your answer and wondered how I got the first error.  in any case.. I am glad you know about it.  The program, for what it does boosts my cpu to 50% so I uninstalled it.  It also needs an uninstaller script.  I had to research how to do that manually.  Luckily it was nicely organized and took only two deletes (saving the fonts).

**Comment by iabem97** [comment]
Hmmm.. Can you tell me about your specs and what wallpaper you had? I'll look into the CPU usage issue.

**Comment by bksubhuti** [comment]
Dual-Core Intel® Celeron® CPU  N3050  @ 1.60GHz
8gb ram
32 gb hard drive 14 for ubuntu
"acer c1yf"

I was a little disappointed to find that there was no android live screen animation.. but on the other hand, that would really eat up laptop battery and cpu.  However, I like the "conky" style of it.  It could have potential to use very little processor time by doing updates every second, .. perhaps detecting if it is the current window and only taking real time animation when the mouse is visible.  But maybe even opting to turn off the "mouse over" animation would also be good.  It has potential.. best of luck.  Let me know when an update is there.  I will test for you.

**Comment by juippis** [comment]
I fixed this error by adding this line, 
>\`pkg-config --cflags --libs glib-2.0 gtk+-3.0 libgtop-2.0\`

Into CMakeLists.txt under
>add_definitions(${CFLAGS} -Wall -Winit-self -Wwrite-strings -Wunreachable-code -Wstrict-prototypes)

not sure if it works better than running cmake twice, for example packagers?

**Comment by iabem97** [comment]
@bksubhuti Thank you. I will work on the CPU usage issues, and I do strongly believe that it is happening because of the wallpaper itself (2 layers of Gdk Pixbuf with a large scale).
As for other animations, more to come soon!

@juippis Not sure how you got it to work? Did you put that inside of a function in CMakeLists.txt
I actually go the issue fixed simply by moving the line:
`pkg_check_modules(DEPS REQUIRED gtk+-3.0 libgtop-2.0 glib-2.0>=2.38)`
to underneath:
`find_package(PkgConfig)`
That solved the problem. Thanks for helping!

**Comment by iabem97** [comment]
I will close this issue since it has been solved.
