### ISSUE TITLE
Wallpaper Creator makes Video wallpapers improperly

### ISSUE THREAD

**Issue by FeelsKnight** [iabem97/komorebi#80]
When Wallpaper Creator makes a Video wallpaper, it creates a folder with the config file, the video and the thumbnail, which is thumb.jpg. A wallpaper created that way doesn't appear in Komorebi. However, it works if you rename thumb.jpg to wallpaper.jpg. So...

Temporary fix for users:
Rename thumb.jpg to wallpaper.jpg.

Permanent fix for dev:
a) Have Wallpaper Creator make wallpaper.jpg thumbnails;
b) Have Komorebi accept thumb.jpg thumbnails.

**Comment by thedonquixotic** [comment]
This issue is well known. please close @FeelsKnight 

I'm trying to clean up the repo and modifying documentation. paring things down. https://github.com/iabem97/komorebi/issues/103
