### ISSUE TITLE
Can't Apply Theme That I Created

### ISSUE THREAD

**Issue by naufaldwi** [iabem97/komorebi#81]
I can't use the theme that I make on komorebi 
![deepinscreenshot_20171115120908](https://user-images.githubusercontent.com/22340411/32819816-e3959824-c9fd-11e7-8a83-f75fae84eaf7.png)
![deepinscreenshot_20171115120929](https://user-images.githubusercontent.com/22340411/32819818-e41c3aa0-c9fd-11e7-8ca8-af929baaa4b4.png)
![deepinscreenshot_20171115120933](https://user-images.githubusercontent.com/22340411/32819821-e487674e-c9fd-11e7-82fe-e38ab2670c49.png)
![deepinscreenshot_20171115120936](https://user-images.githubusercontent.com/22340411/32819822-e501ab08-c9fd-11e7-94c1-0179657ea56c.png)

**Comment by skintigth** [comment]
I have the same issue, I've tried changing permissions, execute as root, using another directory `/System/Resources/Komorebi/WallpaperFolder`and nothing works.

I tried running from terminal to show me some error but noting shows than `wellcome to komorebi`

**Comment by iabem97** [comment]
Thank you for reporting the issue. The issue was that the wallpaper creator was naming the generated file "thumb" instead of "wallpaper". Next push will resolve this.
