### ISSUE TITLE
RAM shows wrong information

### ISSUE THREAD

**Issue by VladimirDev93** [iabem97/komorebi#9]
This doesn't seems legit. Look at the RAM on System Monitor compared to stats from Komorebi.
![screenshot from 2017-02-07 17-59-07](https://cloud.githubusercontent.com/assets/12301022/22701849/2866c9c2-ed5f-11e6-9a8a-6174dea80df7.png)

**Comment by DrMajkrosoft** [comment]
Also I think that simply right-clicking on the desktop is a bad idea. I need the default Ubuntu options.

**Comment by iabem97** [comment]
I'm going to look into the usage issue for the RAM. I noticed that was happening too on another test computer.
As of the right-click, it is not up to me. I believe there's a patch out there for nautilus that let's you have Komorebi (or any other wallpaper manager) and nautilus at the same time.

**Comment by DrMajkrosoft** [comment]
Ok.

**Comment by rkmax** [comment]
it's happening to me too

**Comment by iabem97** [comment]
@rkmax Are you using a version built from source or packaged?

**Comment by rkmax** [comment]
I'm using this version from AUR https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=komorebi which is using the latest release of the repository 0.9.2

**Comment by XenoDaimon** [comment]
Hi, I noticed that too. In fact, using htop I found out that it might take into account buffered and cached RAM. 
![komorebi_ram_behavior](https://user-images.githubusercontent.com/9908206/28426072-5ec63f64-6d72-11e7-9d66-78e830d314a5.png)

**Comment by iabem97** [comment]
RAM + CPU usage have been removed from Komorebi 2.0 for now.
